---
# tasks file for microcks

- name: Get information about the cluster
  set_fact:
    api_groups: "{{ lookup('k8s', cluster_info='api_groups') }}"

# ======================================
# Start with optional MongoDB components
# ======================================

- name: Get an existing MongoDB Secret
  k8s_facts:
    api_version: v1
    kind: Secret
    name: "{{name}}-mongodb-connection"
    namespace: '{{ meta.namespace }}'
  register: mongodb_secret

- name: The MongoDB Secret is present
  when: mongodb_secret.resources|length == 0
  k8s:
    state: present
    force: False
    definition: "{{ lookup('template', 'mongodb-secret.yml') | from_yaml  }}"

- name: The MongoDB PVC is present
  when: mongodb.install|bool and mongodb.persistent|bool
  k8s:
    state: present
    force: False
    definition: "{{ lookup('template', 'mongodb-pvc.yml') | from_yaml  }}"

- name: The MongoDB Deployment is present if mongodb.install == true
  k8s:
    state: "{{ 'present' if mongodb.install|bool else 'absent' }}"
    definition: "{{ lookup('template', 'mongodb-deployment.yml') | from_yaml  }}"

- name: The MongoDB Service is present if mongodb.install == true
  k8s:
    state: "{{ 'present' if mongodb.install|bool else 'absent' }}"
    definition: "{{ lookup('template', 'mongodb-service.yml') | from_yaml  }}"

# ======================================
# Next deal with optional Keycloak components
# ======================================

- name: The Keycloak PVC is present
  when: keycloak.install|bool and keycloak.persistent|bool
  k8s:
    state: present
    force: False
    definition: "{{ lookup('template', 'keycloak-pvc.yml') | from_yaml  }}"

- name: The Keycloak PostgreSQL Deployment is present if keycloak.install == true
  k8s:
    state: "{{ 'present' if keycloak.install|bool else 'absent' }}"
    definition: "{{ lookup('template', 'keycloak-postgres-deployment.yml') | from_yaml  }}"

- name: The Keycloak PostgreSQL Service is present if keycloak.install == true
  k8s:
    state: "{{ 'present' if keycloak.install|bool else 'absent' }}"
    definition: "{{ lookup('template', 'keycloak-postgres-service.yml') | from_yaml  }}"

- name: The Keycloak ConfigMap is present if keycloak.install == true
  k8s:
    state: "{{ 'present' if keycloak.install|bool else 'absent' }}"
    definition: "{{ lookup('template', 'keycloak-config.yml') | from_yaml  }}"

- name: Get an existing Keycloak Secret
  k8s_facts:
    api_version: v1
    kind: Secret
    name: "{{name}}-keycloak-admin"
    namespace: '{{ meta.namespace }}'
  register: keycloak_secret

- name: The Keycloak Secret is present if keycloak.install == true
  when: keycloak_secret.resources|length == 0 or not keycloak.install|bool
  k8s:
    state: "{{ 'present' if keycloak.install|bool else 'absent' }}"
    force: False
    definition: "{{ lookup('template', 'keycloak-secret.yml') | from_yaml  }}"

- name: The Keycloak Deployment is present if keycloak.install == true
  k8s:
    state: "{{ 'present' if keycloak.install|bool else 'absent' }}"
    definition: "{{ lookup('template', 'keycloak-deployment.yml') | from_yaml  }}"

- name: The Keycloak Service is present if keycloak.install == true
  k8s:
    state: "{{ 'present' if keycloak.install|bool else 'absent' }}"
    definition: "{{ lookup('template', 'keycloak-service.yml') | from_yaml  }}"

- name: The Keycloak Route is present if keycloak.install == true and OpenShift
  when: keycloak.install == true and 'route.openshift.io' in api_groups
  k8s:
    state: "{{ 'present' if keycloak.install|bool else 'absent' }}"
    definition: "{{ lookup('template', 'keycloak-route.yml') | from_yaml  }}"

- name: The Keycloak Ingress is present if keycloak.install == true and Kubernetes
  when: keycloak.install == true and 'route.openshift.io' not in api_groups
  k8s:
    state: "{{ 'present' if keycloak.install|bool else 'absent' }}"
    definition: "{{ lookup('template', 'keycloak-ingree.yml') | from_yaml  }}"

# ======================================
# Finish with pure Microcks components
# ======================================

- name: The Microcks ConfigMap object is present
  k8s:
    state: present
    definition: "{{ lookup('template', 'microcks-config.yml') | from_yaml  }}"

- name: The Microcks Deployment is present
  k8s:
    state: present
    definition: "{{ lookup('template', 'microcks-deployment.yml') | from_yaml  }}"

- name: The Microcks Service is present
  k8s:
    state: present
    definition: "{{ lookup('template', 'microcks-service.yml') | from_yaml  }}"

- name: The Microcks Route is present if OpenShift
  when: "'route.openshift.io' in api_groups"
  k8s:
    state: present
    definition: "{{ lookup('template', 'microcks-route.yml') | from_yaml  }}"

- name: The Microcks Ingress is present if Kubernetes
  when: "'route.openshift.io' not in api_groups"
  k8s:
    state: present
    definition: "{{ lookup('template', 'microcks-ingress.yml') | from_yaml  }}"

- name: The Postman-runtime Deployment is present
  k8s:
    state: present
    definition: "{{ lookup('template', 'postman-runtime-deployment.yml') | from_yaml  }}"

- name: The Postman-runtime Service is present
  k8s:
    state: present
    definition: "{{ lookup('template', 'postman-runtime-service.yml') | from_yaml  }}"
