- hosts: localhost
  gather_facts: no
  vars:
    keycloak_url: http://keycloak
    meta:
      namespace: microcks-operator-test
  pre_tasks:
    - debug:
        var: test
      vars:
        test: "{{ lookup('template', './k8s/microcks-deployment.yml') | from_yaml  }}"

    - fail:

    - name: Get information about the cluster
      set_fact:
        api_groups: "{{ lookup('k8s', cluster_info='api_groups') }}"

    - name: The Microcks Deployment is present
      k8s:
        state: present
        definition: "{{ lookup('template', './k8s/microcks-deployment.yml') | from_yaml  }}"
      
    - debug:
        var: res
      vars:
        res: Result

    - fail:
  roles:
    - microcks