kind: Service
apiVersion: v1
metadata:
  name: "{{name}}-keycloak"
  namespace: '{{ meta.namespace }}'
  labels:
    app: "{{name}}"
    container: keycloak
    group: microcks
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: keycloak
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: "{{name}}"
    container: keycloak
    group: microcks
---
kind: Service
apiVersion: v1
metadata:
  name: "{{name}-keycloak-postgresql"
  namespace: '{{ meta.namespace }}'
  labels:
    app: "{{name}}"
    container: keycloak-postgresql
    group: microcks
spec:
  ports:
  - name: postgresql
    protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 0
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: "{{name}}"
    container: keycloak-postgresql
    group: microcks