kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: "{{name}}-keycloak"
  namespace: '{{ meta.namespace }}'
  labels:
    app: "{{name}}"
    group: microcks
spec:
{% if 'url' in keycloak %}
  host: {{keycloak.url}}
{% endif %}
  to:
    name: "{{name}}-keycloak"
    kind: Service
  port:
    targetPort: keycloak
  tls:
    termination: edge