kind: Service
apiVersion: v1
metadata:
  name: "{{name}}-keycloak-postgresql"
  namespace: '{{ meta.namespace }}'
  labels:
    app: "{{name}}"
    container: keycloak-postgresql
    group: microcks
spec:
  ports:
    - name: keycloak-postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: "{{name}}"
    container: keycloak-postgresql
    group: microcks