kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: "{{name}}"
  namespace: '{{ meta.namespace }}'
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  labels:
    app: "{{name}}"
    group: microcks
spec:
  rules:
  - host: "{{microcks.url}}"
    http:
      paths:
      - backend:
          serviceName: "{{name}}"
          servicePort: 8080