kind: Service
apiVersion: v1
metadata:
  name: "{{name}}"
  namespace: '{{ meta.namespace }}'
  labels:
    app: "{{name}}"
    container: spring
    group: microcks
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: spring
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: "{{name}}"
    container: spring
    group: microcks