kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: "{{name}}"
  namespace: '{{ meta.namespace }}'
  labels:
    app: "{{name}}"
    group: microcks
spec:
{% if 'url' in microcks %}
  host: {{microcks.url}}
{% endif %}
  to:
    name: {{name}}
    kind: Service
  port:
    targetPort: spring
  tls:
    termination: edge