kind: Secret
apiVersion: v1
metadata:
  name: "{{name}}-mongodb-connection"
  namespace: '{{ meta.namespace }}'
  labels:
    app: "{{name}}"
    container: mongodb
    group: microcks
type: kubernetes.io/basic-auth
stringData:
  {% if 'username' in mongodb %}username: '{{mongodb.username}}'
  {% else %}username: user{{ lookup('password', '/dev/null length=5 chars=ascii_letters') }}
  {% endif %}
data:
  {% if 'password' in mongodb %}password: {{ mongodb.password | b64encode | quote }}
  {% else %}password: {{ lookup('password', '/dev/null length=32 chars=ascii_letters') | b64encode | quote }}
  {% endif %}{% if 'adminPassword' in mongodb %}adminPassword: {{ mongodb.adminPassword | b64encode | quote }}
  {% else %}adminPassword: {{ lookup('password', '/dev/null length=32 chars=ascii_letters') | b64encode | quote }}
  {% endif %}
