kind: Service
apiVersion: v1
metadata:
  name: "{{name}}-postman-runtime"
  namespace: '{{ meta.namespace }}'
  labels:
    app: "{{name}}"
    container: postman-runtime
    group: microcks
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
      name: postman-runtime
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: "{{name}}"
    container: postman-runtime
    group: microcks