apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: microcks.microcks.github.io
spec:
  group: microcks.github.io
  names:
    kind: Microcks
    listKind: MicrocksList
    plural: microcks
    singular: microcks
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
